"""Fix transactions relationship

Revision ID: ae61ce21dd5c
Revises: eb476869ebe1
Create Date: 2024-11-05 09:26:19.904592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae61ce21dd5c'
down_revision = 'eb476869ebe1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.alter_column('portfolioId',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.alter_column('portfolioId',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
