"""create stocks table

Revision ID: 001652c77aaa
Revises: 31079fe82ea8
Create Date: 2024-11-03 12:56:44.735499

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '001652c77aaa'
down_revision = '31079fe82ea8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stocks',
    sa.Column('name', sa.String(length=5), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.String(length=2), nullable=False),
    sa.Column('price', sa.String(length=6), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('name', 'portfolio_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stocks')
    # ### end Alembic commands ###
